### ISSUE TITLE
set description of issue not just add comment

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus-github-lottery#44]
My issue at https://github.com/quarkusio/quarkus-github-lottery-reports/issues/8 is getting quite long and requires lot of scrolling just to get to the end of it.

How about updating the description of the issue with last comment so when clicking the link you don't need to scroll all the way down?

**Comment by yrodiere** [comment]
The idea was that you would have everything in the notification email, so you don't really *need* to read it on GitHub directly.

We need the comments in order to send those email notifications, but yes, if you think it's useful we could also update the issue's description to match the latest comment.

**Comment by maxandersen** [comment]
It would be nice since I don't use the notification emails but rather GitHub notifications and here the focus is on the description when you click the link. 

Thus for this specific usecase it would be nice having the issue description updated in sync with the last comment.

**Comment by yrodiere** [comment]
@maxandersen Done, you should get the last comment in the issue description on your next notification (this Friday, from what I can see).

**Comment by maxandersen** [comment]
Awesome!
